version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - FLASK_env=development
      - FLASK_APP=app.py
      - DB_HOST=localhost
      - DB_USER=username
      - DB_PASSWORD=password
      - DATABASE_URL=mysql+pymysql://myuser:mypassword@localhost:3306/twoge_db
    depends_on:
      - db
    command: python app.py
  # db: 
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_DATABASE: twoge_db
  #     MYSQL_USER: twoge_user
  #     MYSQL_PASSWORD: twoge_pass
  #     MYSQL_ROOT_PASSWORD: rootpass
  #   ports:
  #     - "3306:3306"